### PR TITLE
rpc: add optional default context for server responses

### PR DESCRIPTION
**Pull request by riscdanger**
This pushes up when `rpc.Server` builds its default context from the private `respond()` in a tight loop, to `Respond()` which gets called once per `ServeMux()` call. It also add a `Context` field to `rpc.Server`, useful for setting a response deadline with `context.WithDeadline()`. It's also fairly common to add db clients, loggers, etc to the context for use by server handlers.

### CODE REVIEW

**Comment by riscdanger** [comment]
Seeing how this is used in Tractor, perhaps the extra server field is not necessary, and should be set in the server code and not qtalk.

**Comment by progrium** [comment]
i almost did this but yea if it can be done outside qtalk it might be better, though this is nice. just want to avoid the pattern of keeping contexts in struct fields. i thought about adding argument to the ServeMux et al methods, but was trying to minimize changes downstream. wanna see if you can get by without and leave this until you get a better feel?

**Comment by riscdanger** [comment]
Sounds good. I should've started in Tractor :)

**Comment by progrium** [comment]
closing since this solves a problem the API doesn't have

**Pull request closed without merging**
